# Generated by Django 4.2.6 on 2023-10-23 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task2",
        ),
    ]
